### ISSUE TITLE
★학교 소식을 전달하고 받아보는 '학교소식 뉴스피드'

### ISSUE THREAD

**Issue by sodaMelon** [sodaMelon/news-feed#1]
# 🎈GOAL
#### 학교 관리자는 학교를 페이지를 운영하여 학교 소식을 발행할 수 있다.
- [x] 학교 관리자는 지역, 학교명으로 학교 페이지를 생성할 수 있다. [issue#4](https://github.com/sodaMelon/news-feed/issues/4)
- [x] 학교 관리자는 학교 페이지 내에 소식을 작성할 수 있다. [issue#8](https://github.com/sodaMelon/news-feed/issues/8)
- [x] 학교 관리자는 작성된 소식을 삭제할 수 있다. issue#8
- [x] 학교 관리자는 작성된 소식을 수정할 수 있다. issue#8

#### 학생은 학교 페이지를 구독하여 학교 소식을 받아 볼 수 있다. (※학교별 소식은 최신순으로 노출해야 함)
- [x] 학생은 학교 페이지를 구독할 수 있다. [issue#10](https://github.com/sodaMelon/news-feed/issues/10)
- [x] 학생은 구독 중인 학교 페이지 목록을 확인할 수 있다. issue#10
- [x] 학생은 구독 중인 학교 페이지를 구독 취소할 수 있다. issue#10
- [x] 학생은 구독 중인 학교(페이지)별 소식을 볼 수 있다.[issue#12](https://github.com/sodaMelon/news-feed/issues/12)

#### 학생은 구독 중인 학교 소식을 자신의 뉴스피드에서 모아볼 수 있다. [issue#14](https://github.com/sodaMelon/news-feed/issues/14)
- [x] 구독중인 모든 학교의 소식을 모아볼 수 있어야 함 issue#14
- [x] 학교 소식이 노출되는 뉴스피드는 최신순으로 소식을 노출 issue#14
- [x] 학교 페이지를 구독하는 시점 이후 소식부터 뉴스피드를 받음 issue#14
- [x] 학교 페이지 구독을 취소해도 기존 뉴스피드에 나타난 소식은 유지해야 함 issue#14

**Comment by sodaMelon** [comment]
[채택 이유]
- Spring boot : 익숙함.. ( nestJS ? 를 써보고 싶었으나, JS진영쪽 테스트&API문서자동화 툴을 안써봄+ 기간에 비해 작업량이 많아질 것 같아서 포기)
- Spring Rest DOCS : 통합 테스트 환경 구성 시, 테스트가 성공해야 API가이드 문서가 자동생성됨. (작업 생산성과 커버리지..측정 시에 괜찮아보였음.) 
- JPA : ORM+ 특정 DB SQL에 의존하지 않음. ( 예 : Oracle DB와 MySQL의 문법차이..)
- QueryDsl : [issue#17](https://github.com/sodaMelon/news-feed/issues/17)에도 썼는데, 현재 환경 구성에 적합하므로 추가 채택함. (코드로 쿼리를 작성하기 때문에, 컴파일 시점에 오류 확인 가능.)
